import { AchievementDefinition } from '../types';

export const ACHIEVEMENTS: AchievementDefinition[] = [
  // Learning
  {
    id: 'first_lesson',
    name: 'First Steps',
    description: 'Complete your first lesson',
    icon: '📖',
    category: 'learning',
    xpReward: 25,
    condition: { field: 'lessonsCompleted', threshold: 1 },
  },
  {
    id: 'ten_lessons',
    name: 'Bookworm',
    description: 'Complete 10 lessons',
    icon: '📚',
    category: 'learning',
    xpReward: 100,
    condition: { field: 'lessonsCompleted', threshold: 10 },
  },
  {
    id: 'fifty_lessons',
    name: 'Scholar',
    description: 'Complete 50 lessons',
    icon: '🎓',
    category: 'learning',
    xpReward: 250,
    condition: { field: 'lessonsCompleted', threshold: 50 },
  },
  {
    id: 'hundred_lessons',
    name: 'History Buff',
    description: 'Complete 100 lessons',
    icon: '🏛️',
    category: 'learning',
    xpReward: 500,
    condition: { field: 'lessonsCompleted', threshold: 100 },
  },
  // Streak
  {
    id: 'streak_3',
    name: 'On a Roll',
    description: 'Reach a 3-day streak',
    icon: '🔥',
    category: 'streak',
    xpReward: 50,
    condition: { field: 'longestStreak', threshold: 3 },
  },
  {
    id: 'streak_7',
    name: 'Week Warrior',
    description: 'Reach a 7-day streak',
    icon: '💪',
    category: 'streak',
    xpReward: 100,
    condition: { field: 'longestStreak', threshold: 7 },
  },
  {
    id: 'streak_30',
    name: 'Monthly Master',
    description: 'Reach a 30-day streak',
    icon: '⭐',
    category: 'streak',
    xpReward: 300,
    condition: { field: 'longestStreak', threshold: 30 },
  },
  {
    id: 'streak_100',
    name: 'Centurion',
    description: 'Reach a 100-day streak',
    icon: '👑',
    category: 'streak',
    xpReward: 1000,
    condition: { field: 'longestStreak', threshold: 100 },
  },
  // Mastery
  {
    id: 'perfect_lesson_1',
    name: 'Perfectionist',
    description: 'Get a perfect score on a lesson',
    icon: '💯',
    category: 'mastery',
    xpReward: 50,
    condition: { field: 'perfectLessons', threshold: 1 },
  },
  {
    id: 'perfect_lesson_10',
    name: 'Flawless',
    description: 'Get 10 perfect scores',
    icon: '🌟',
    category: 'mastery',
    xpReward: 200,
    condition: { field: 'perfectLessons', threshold: 10 },
  },
  {
    id: 'era_complete',
    name: 'Era Expert',
    description: 'Complete all lessons in an era',
    icon: '🗺️',
    category: 'mastery',
    xpReward: 500,
    condition: { field: 'erasCompleted', threshold: 1 },
  },
  // Level
  {
    id: 'level_5',
    name: 'Rising Star',
    description: 'Reach level 5',
    icon: '🌱',
    category: 'level',
    xpReward: 50,
    condition: { field: 'level', threshold: 5 },
  },
  {
    id: 'level_10',
    name: 'Seasoned Learner',
    description: 'Reach level 10',
    icon: '🌿',
    category: 'level',
    xpReward: 100,
    condition: { field: 'level', threshold: 10 },
  },
  {
    id: 'level_25',
    name: 'History Master',
    description: 'Reach level 25',
    icon: '🌳',
    category: 'level',
    xpReward: 500,
    condition: { field: 'level', threshold: 25 },
  },
  // XP
  {
    id: 'xp_1000',
    name: 'XP Hunter',
    description: 'Earn 1,000 XP',
    icon: '💰',
    category: 'xp',
    xpReward: 50,
    condition: { field: 'xp', threshold: 1000 },
  },
  {
    id: 'xp_10000',
    name: 'XP Legend',
    description: 'Earn 10,000 XP',
    icon: '💎',
    category: 'xp',
    xpReward: 250,
    condition: { field: 'xp', threshold: 10000 },
  },
];
